<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{802f884d-54f5-444a-9d44-2eadbfbf0423}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CASE GVL.nProgramID OF
	0 : Reset();
	1 : V0_1();
	2 : V0_2();
	3 : V0_3();
END_CASE]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="50" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="61" Count="1" />
      <LineId Id="64" Count="0" />
      <LineId Id="57" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>