<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="V0_1" Id="{eb38a907-3839-4f11-90aa-f3f66742f237}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM V0_1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL.bLamp_1 := GVL.bButton_1;]]></ST>
    </Implementation>
    <LineIds Name="V0_1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>